package obligatorio2.ui;

import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuItem_LoginAgenda = new javax.swing.JMenuItem();
        mnuItem_LoginAdministrador = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuItem_Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Principal");

        mnuItem_LoginAgenda.setText("LoginAgenda");
        mnuItem_LoginAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItem_LoginAgendaActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItem_LoginAgenda);

        mnuItem_LoginAdministrador.setText("LoginAdministrador");
        mnuItem_LoginAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItem_LoginAdministradorActionPerformed(evt);
            }
        });
        jMenu1.add(mnuItem_LoginAdministrador);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Aplicacion");

        mnuItem_Salir.setText("Salir");
        mnuItem_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItem_SalirActionPerformed(evt);
            }
        });
        jMenu2.add(mnuItem_Salir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItem_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItem_SalirActionPerformed
        salir();
    }//GEN-LAST:event_mnuItem_SalirActionPerformed

    private void mnuItem_LoginAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItem_LoginAgendaActionPerformed
        loginJuego();
    }//GEN-LAST:event_mnuItem_LoginAgendaActionPerformed

    private void mnuItem_LoginAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItem_LoginAdministradorActionPerformed
        loginAdministrador();
    }//GEN-LAST:event_mnuItem_LoginAdministradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuItem_LoginAdministrador;
    private javax.swing.JMenuItem mnuItem_LoginAgenda;
    private javax.swing.JMenuItem mnuItem_Salir;
    // End of variables declaration//GEN-END:variables

    private void salir() {
        int option = JOptionPane.showConfirmDialog(this, "Desea Salir?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    private void loginJuego() {
        Login login = new LoginJuego(this, false) {};
        login.setVisible(true);
        login.setLocationRelativeTo(this);
    }

    private void loginAdministrador() {
        Login login = new LoginAdministrador(this, false);
        login.setVisible(true);
        login.setLocationRelativeTo(this);
    }
}
